### ISSUE TITLE
There is a problem in the build.gradle of Groovy syntax

### ISSUE THREAD

**Issue by javakam** [natario1/MavenPublisher#11]
In My build.gradle : 
```
sonatype("") {
    auth.user = "xxx"
    auth.password = "xxx"
}
```
caused :
```
A problem occurred evaluating project ':library'.
> No such property: user for class: io.deepmedia.tools.publisher.common.Auth
```

**Comment by natario1** [comment]
The auth object is an instance of `io.deepmedia.tools.publisher.sonatype.SonatypeAuth`, a subclass of `io.deepmedia.tools.publisher.common.Auth`. I'm not confident with groovy so I'm not sure what's the issue here. If you find a solution feel free to post here or open a PR.

**Comment by javakam** [comment]
Thank you for your reply, I found another suitable solution 👉 <https://proandroiddev.com/publishing-your-first-android-library-to-mavencentral-be2c51330b88>
