### ISSUE TITLE
Unable to load GPG key from local.properties

### ISSUE THREAD

**Issue by sasa-b** [natario1/MavenPublisher#26]
Hey there, I've followed your blog post https://blog.deepmedia.io/post/how-to-publish-to-maven-central-in-2024 but no matter what I do I'm unable to load the GPG key.

I keep getting this error `Cause: secret key ring doesn't start with secret key tag: tag 0xffffffff`. With or without `\n` line character, I've tried escaping the `\\n` and putting the key between `""` but it still doesn't help.

**Comment by natario1** [comment]
Where are you loading the GPG key from?

**Comment by sasa-b** [comment]
@natario1 I tried loading it from `local.properties / gradle.properties` 

I also tried populating the ENV as well with `System.setProperty("SIGNING_KEY", File("key.txt").readText())` and removing it from local.properties but I got the same error.

**Comment by natario1** [comment]
Here's how the key should look like in `.properties` files. Note that newlines are simple `\n`.

Beginning:
<img width="504" alt="Screenshot 2024-11-12 alle 12 35 30" src="https://github.com/user-attachments/assets/6a416543-501e-4818-8dc3-29f28194615e">

End:
<img width="395" alt="Screenshot 2024-11-12 alle 12 35 59" src="https://github.com/user-attachments/assets/c07bac72-1b7d-455f-9ada-c21bc4550191">

If your key looks similar, maybe you are using the wrong password.

**Comment by sasa-b** [comment]
@natario1 thank you very much for the prompt responses, the issue was that I didn't start with the newline special character `SIGNING_KEY=\n...` 🤦‍♂️
